apiVersion: apps/v1 ##testing
kind: Deployment
metadata:
  name: my-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deploy
  template:
    metadata:
      labels:
        app: my-deploy
    spec:
      containers:
      - name: my-container
        image: sujeetsr07/my-img:latest
        imagePullPolicy: Never
