apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-deploy
  name: my-deploy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30200
  selector:
    app: my-deploy
  type: NodePort
status:
  loadBalancer: {}
